sudo: false
dist: bionic
language: cpp
compiler:
  - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - g++-4.8 --version
  - g++ --version
#  - export CXXSUFFIX=-4.8

script:
  - make
  - make clean
  - make debug
